@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNDZhY2JlMS01Y2U4LTQ3YzUtYWUwNC0wY2Q0Yzg4NGNmNTYiLCJ1bmlxdWVfbmFtZSI6IjA0NmFjYmUxLTVjZTgtNDdjNS1hZTA0LTBjZDRjODg0Y2Y1NiIsImp0aSI6IjJlY2ZjMDAxLTM5YmQtNGExZC1hMmY5LTA0NzBlNGMxMmRlYyIsImlhdCI6IjE1NDY3NDc3NTg2NTUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTU0Njc0Nzc1OCwiZXhwIjoxNTQ2NzQ5NTU4LCJpc3MiOiJsaWNlbnNlLW1hbmFnZXItaWRlbnRpdHktc2VydmljZSJ9.bp63phgt3ANzXjxYaD9QZsDfOTC3h5LxFb6eyFD_Fkk

####
@refreshToken = AQAAAAEAACcQAAAAEDPdNm3P3WZcp6zKvDZepgeXZkzyFgeRLgQu8MyQf1gelHCvR0m6ldUvFWiew


###
POST https://localhost:5001/api/sign-up
content-type: application/json

{
  "email": "user1@mailinator.com",
  "userName": "user1",
  "password": "secret",
}

###
POST https://localhost:5001/api/sign-in
content-type: application/json

{
  "email": "user1@mailinator.com",
  "password": "secret"
}

###
POST http://localhost:5000/api/refreshToken/{{refreshToken}}/refresh

###
GET http://localhost:5000/api/license/323BF0A9-16C2-48BC-8D80-0888FA854142
authorization: Bearer {{token}}

###
POST http://localhost:5000/api/license
authorization: Bearer {{token}}
Content-Type: application/json

{
  "ip": "558.152.155.122",
  "hwid": "566684023544545",
  "key": "565ds4dds8d8sd5sd4ad6sa4d"
}

###
GET http://localhost:5000/api/license?page=2&results=1
authorization: Bearer {{token}}

###
POST https://localhost:5001/api/license/change-status
authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "323BF0A9-16C2-48BC-8D80-0888FA854142",
  "status": "Active"
}